### ISSUE TITLE
Intent to relicense under MIT license

### ISSUE THREAD

**Issue by djzort** [djzort/perl-WebService-HashiCorp-Vault#11]
See also https://en.wikipedia.org/wiki/MIT_License and https://metacpan.org/pod/Software::License::MIT

Contributors need to sign off...

@amishHammer 

Commits:
c649232be537af4f1e57a0568475fc6f4f5ce640
ef066ae3097f546fb0cd803f024f58bc0611056b

@nxadm 

Commits:
7380caeb5e9959412fcb3d7cbfd68ab9b0cd18c1
599cf51aafec29f7a6f4926b332512b345799cf9
47200071459ed5f80564141b2f654e0008e425d4
3d3058e134614c030bcd1c6328802aa1eed95de2

**Comment by nxadm** [comment]
Feel free to re-license my (trivial) commits.

**Comment by djzort** [comment]
@yewtc please confirm you are ok to re-license to MIT as this has not yet recieved confirmation for all authors 

636f8aea52ec54b21dd6420f7b02959535ef0adc
7200837548e64a66ef594f91968843c91f0d5ace
9ad6da3cf7bcbba9bd2eb6cc3aa6003bcc91a214

**Comment by amishHammer** [comment]
Sorry for the delayed response. Re-licensing of my commits is fine.

**Comment by yewtc** [comment]
Also sorry for the delay- more than happy to relicense.

**Comment by djzort** [comment]
Completed it b4d281f3c3d39ef2f00fd8dd1e1f708c18240bef
